### ISSUE TITLE
Time tracking state is displayed in cards

### ISSUE THREAD

**Issue by almereyda** [hkgnp/logseq-kanban-plugin#2]
The cards display time tracking metadata within their titles.

![logseq-kanban-todo-tracking](https://user-images.githubusercontent.com/1645308/145912217-68e1024b-e3ce-419e-9f3a-74ab93567a80.png)

**Comment by hkgnp** [comment]
Ooo, I've not considered this use case.
How do you activate time tracking in Logseq?

**Comment by almereyda** [comment]
The time tracking metadata appears in blocks, when one uses the /TODO /NOW /DOING /LATER /DONE slash commands. Imagine you create a /TODO, then clicking onto its bold and linked description text next to the checkbox will toggle it to be DOING instead (depending on your workflow settings). While it is in this state, its time is recorded. Then clicking that again will switch it back to TODO mode, and stop recording time. This can be repeated at will. Checking the box will mark the task as DONE, and display the total time worked on it.

**Comment by hkgnp** [comment]
I tried to replicate it, but I was not able to. Are you on the latest version from the marketplace, please?

![Screenshot 2021-12-15 at 11 56 16 AM](https://user-images.githubusercontent.com/47936793/146120429-e5f0efb9-c7ca-4ec3-96ea-884a49d4e3e5.png)

For this plugin, I've only configured it for TODO, DOING and DONE. I've not configured it for the rest actually.

**Comment by hkgnp** [comment]
Closing this issue since no update. Please re-open if needed.

**Comment by lachlancresswell** [comment]
Opening this issue as it is still happening as of latest Logseq and logseq-kanban-plugin versions.

![logseqbug](https://user-images.githubusercontent.com/18381424/149606698-88192fa6-73de-4fa7-829d-dff9cbe41ed2.gif)

**Comment by hkgnp** [comment]
![demo](https://user-images.githubusercontent.com/47936793/149607929-33059c64-b967-4072-80ec-c813d15d74d5.gif)

I don't seem to be getting this issue. I am not sure if you have other plugins or settings enabled that I've not. Could you share if so?

**Comment by happy15** [comment]
happens to me either, logseq v0.5.9 with logseq kanban plugin v2.41.

**Comment by hkgnp** [comment]
@happy15 @lachlancresswell I realised why! I don't use timetracking in Logseq so I never got this issue.

Fixed this in v2.5 (I hope). Do you mind having a go to see if it's fixed?

**Comment by happy15** [comment]
> @happy15 @lachlancresswell I realised why! I don't use timetracking in Logseq so I never got this issue.
> 
> Fixed this in v2.5 (I hope). Do you mind having a go to see if it's fixed?

happy to do that, but the market place only has v2.41. how to manually install v2.5?

**Comment by happy15** [comment]
manually installed v2.5, but the installed plugin section in market place still shows v2.41. I restarted logseq, it still doesn't work.

**Comment by hkgnp** [comment]
Hmm, the marketplace version shows v2.5 for me. Can you try clicking "Check Update" again?

If you are on v2.5 and it still shows not fixed, please take a screenshot for me to have a look.

Thanks!

**Comment by happy15** [comment]
v2.5 fixed this issue in my case.

it turns out I have to delete the v2.41 installed from market place and then installed it manually.

**Comment by hkgnp** [comment]
Great! Happy to hear that it now works!
Thanks for your patience!

**Comment by almereyda** [comment]
It seems we should file an issue upstream when plugin updates don't work, which I am doing right now.

**Comment by hkgnp** [comment]
Thanks for doing so!
